1. Swap deprecated pedantic for lints
appwrite/functions-starter pull request #31
Opened 2022-07-06 16:43 UTC by noga-dev

2. Remove linter warnings by commenting out the code causing them
3. Add suggestion above the code that was causing linter warnings
3. Use final to encourage immutability

2022-07-06 16:43 UTC, noga-dev commented
The lints over pedantic are due to its deprecation per the description in the package page: https://pub.dev/packages/pedantic

2022-07-06 17:01 UTC, noga-dev commented
5. Added analysis_options.yaml otherwise lint rules won't take effect

2022-10-07 15:45 UTC, stnguyen90 requested changes
Thanks for the PR! 🙏 Unfortunately, it looks like there are merge conflicts now. Would you please fix the merge conflicts?

2022-10-07 18:47 UTC, stnguyen90 approved these changes

2022-10-09 01:19 UTC, lohanidamodar requested changes
please fix the comment

2022-10-09 01:19 UTC, lohanidamodar commented on dart-2.12/pubspec.yaml
> +  lints: ^2.0.0
lints 2.0 requires Dart SDK 2.17 so this dart 2.12 starter shouldn't use lints 2.0.0

2022-10-09 01:19 UTC, lohanidamodar commented on dart-2.13/pubspec.yaml
> +  lints: ^2.0.0
same as above

2022-10-21 00:56 UTC, lohanidamodar requested changes, later dismissed
Looks good. Just that 2.0.1 is released let's update to that and get this merged.

2022-10-21 06:31 UTC, noga-dev commented
> Looks good. Just that 2.0.1 is released let's update to that and get this merged.

2.0.1 of?

2022-10-21 06:59 UTC, christyjacob4 commented
@noga-dev `2.0.1` of the lints package has been released 😄  Please update to that 
https://pub.dev/packages/lints/versions

2022-10-21 07:26 UTC, noga-dev commented
> @noga-dev `2.0.1` of the lints package has been released 😄 Please update to that https://pub.dev/packages/lints/versions

Done

2022-10-21 20:02 UTC, christyjacob4 approved these changes

2022-10-21 20:03 UTC, merged

2022-10-21 20:03 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)