Feat: Dart 3.1
appwrite/functions-starter pull request #58
Opened 2023-10-16 15:52 UTC by Meldiron

## What does this PR do?

Starter for Dart 3.1

## Test Plan

None

## Related PRs and Issues

X

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-10-16 19:48 UTC, christyjacob4 commented on dart-3.1/lib/main.dart
> +    'motto': 'Build Fast. Scale Big. All in One Place.',
```suggestion
    'motto': 'Build like a team of hundreds_',
```
Might wanna change this in all runtimes

2023-10-16 19:48 UTC, christyjacob4 commented on dart-3.1/README.md
> +  "motto": "Build Fast. Scale Big. All in One Place.",
```suggestion
  "motto": "Build like a team of hundreds_",
```
Here as well

2023-10-16 19:49 UTC, christyjacob4 requested changes
Looks good. Just a small comment

2023-10-17 07:31 UTC, Meldiron commented on dart-3.1/lib/main.dart
> +    'motto': 'Build Fast. Scale Big. All in One Place.',
Updated everywhere

2023-10-17 07:32 UTC, Meldiron commented on dart-3.1/README.md
> +  "motto": "Build Fast. Scale Big. All in One Place.",
Updated everywhere

2023-10-17 08:42 UTC, christyjacob4 approved these changes

2023-10-17 08:42 UTC, merged